### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Courtcircuits** [DO-2K23-26/beep-rtc#4]
Create config file to manage application

```yaml
global:
  sfu_workers:
     min_port:
     max_port:
  signal_port:
prod:
   log_level:
   loki:
      enabled: true
      endpoint: "<loki-endpoint>"
dev:
   log_level:
```
